---
- block:

    - name: install dependencies
      package:
        name: unzip
        state: present

    - name: create install path
      file:
        state: directory
        path: "{{ typesafe_activator_install_root }}"
        mode: "0755"
        owner: "{{ typesafe_activator_user }}"
        group: "{{ typesafe_activator_group }}"

    - name: install package
      unarchive:
        creates: "{{ typesafe_activator_install_root }}/activator-dist-{{ typesafe_activator_version }}/bin/activator"
        remote_src: true
        src: "{{ typesafe_activator_dl_uri }}"
        dest: "{{ typesafe_activator_install_root }}"
        owner: "{{ typesafe_activator_user }}"
        group: "{{ typesafe_activator_group }}"

    - name: link to versioned dir
      file:
        state: link
        src: "{{ typesafe_activator_install_root }}/activator-dist-{{ typesafe_activator_version }}"
        dest: "{{ typesafe_activator_install_root }}/typesafe-activator"
        owner: "{{ typesafe_activator_user }}"
        group: "{{ typesafe_activator_group }}"

    - name: fix activator missing a+x
      file:
        state: file
        path: "{{ item }}"
        mode: "0755"
      with_items:
        - "{{ typesafe_activator_install_root }}/activator-dist-{{ typesafe_activator_version }}/bin/activator"
        - "{{ typesafe_activator_install_root }}/activator-dist-{{ typesafe_activator_version }}/bin/activator-dist"

  become: true
  tags:
    - typesafe-activator
